# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'
cache:
  directories:
  - $HOME/.yarn-cache
before_install:
  - npm install --global yarn
install:
  - yarn
