# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

language: node_js
node_js:
  - '6'
  - '8'
  - 'stable'
cache: yarn

# Make Greenkeeper work with lockfiles:
# https://github.com/greenkeeperio/greenkeeper-lockfile/tree/f62f2f3e33cd1dd349c2898e0129c693cbc5804d#yarn
env:
  global:
    secure: cjR7miSEmLLb2rvbPqHs6m1Dl78DBz/JU4WqtVpSpIhXPGrnxtiiwRBwQS0OK8NJ0ga53YVDpfwx9OPZleIBRNwnxo1HTRlE6+GzPA4Jcp5AbRBgpkoPFjEBQ0pXpubBmVqMZxVPJ1e+v/CebfS/S4rszUokBLBQwui5fyl9fZvZFe9/bAfU7wr5Dd47YstsyrxLx1cKrUaLmimEGKXBbeeWdl3AK4hOJmkaQ6tPGll656rCkKnRoKsXKBiH3An7wwje0lt1keSaLZJKLcwsqhPjcyblqCOagZiIOf5jPL8scTSGI3jFhryCwCSaEUriBeYOT+vyyJtXEjDe8JJMJyXiu3acQBgAp1sDZfBvb+RsYkJOSRyy6qTTYeL5qE6S3tTm7u47bng+s3rys+LEmpHtSlxtuTc+dbTBfx3s4oHHcQuoD2yT0lQFsER/4yrwJCzw8lbB0RTP1oSt0n7LC6r5w0R6qqPEJDcKCJq5z+BTBrlMYvZRppmIDA6jYxz8cnAbDHcw0J95nk9p6ZC0KHIpD169TxGTKg/S8lHXU2zCIsvMHGRuagl44AMu94LAH4KPnX/EUV+1PHVvuvZSUkQkJ25AmElhhdGryEQHJFBkFhnZluqmPgXaVqkVMj6HCH18q+OA0MwRh9U24x4F8VyCq7qbcXR8kLcnNwNLeUo=

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
