# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'
cache: yarn

# Make Greenkeeper work with lockfiles:
# https://github.com/greenkeeperio/greenkeeper-lockfile/tree/f62f2f3e33cd1dd349c2898e0129c693cbc5804d#yarn
env:
  global:
    secure: cURuDeH8lQo71U1jxO2HVBgBk9fYrS76KR/a/UZ5RD6GlgSLJ/hca/8tuH1+IxF90276xlOqPqwI8WGcvepuQWvSa/3MjX23Al1s9Ssam/yQBtwrCBqfjNvQWQhxHYFV1TGia4BxmptWun5uX36ykw8MptmLRr99lyTQVKpw4ngYCQH9hBvfSlyLVPUEnfWIcHZ3IXJAPrgP1gkSzEl677IcMFxSM3527VtkIWWtl9ydEeYYblfyu5+A31TDp3tIokhAewTaxLHvdIRKptkMkxN1SWtP9XzjBYr1cXE+vS+rQ0H3Y3ItuKnXLXHlI4uEgLddvbK2zbRfYfD5WHFCSc+e7KeUeIOAsZcpGk/tjlG0F3lI43NW0Lmh2ImHQ4N505FhCHjLFgecDOE8yB/9iXHJP1CpDm1d0B37aK2w1O9xdhNHKe4mSttg5tSkZTPtXkYJ0BY1mb3MfHYTKuEQuljtOM+xHnsanPqdlSuKSsH3T5VPS6YWH6K+rLs+9fy8J7ZN8BxqOWbWyZA43s7cB4iNtqRoyu2nxzHVnmCGE7BSZmSF+KgrGqjmIVFa55ggtmdEmwBAoNq8xXhJZKA4twecECkAhoPE+ianuIanM+DdeewWjUTfz+CZCVlYaDL67YfQo8uY1A2sWYm+jSfWFCps9PNWhV8I1zN0iPjhjHo=

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
