# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

language: node_js
node_js:
  - '4'
  - 'stable'
cache:
  directories:
  - node_modules
install:
  - npm prune && npm install
