environment:
  matrix:
    - nodejs_version: '' # latest
    - nodejs_version: '14'
    - nodejs_version: '12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global pnpm@5.10.2
  - pnpm install

test_script:
  - node --version
  - pnpm --version
  - pnpm test

# Disable MSBuild
build: off
