environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"

cache:
  - "%LOCALAPPDATA%/Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install yarn
  - refreshenv
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

# Disable MSBuild
build: off
