environment:
  matrix:
    - nodejs_version: '' # latest
    - nodejs_version: '14'
    - nodejs_version: '12'

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

# Disable MSBuild
build: off
